export const routes = [
    {
        path: '/login',
        name: 'login',
        component: () => import('@/views/auth/LoginView.vue'),
        meta: { requiresAuth: false, guestOnly: true },
    },
    {
        path: '/register',
        name: 'register',
        component: () => import('@/views/auth/RegisterView.vue'),
        meta: { requiresAuth: false, guestOnly: true },
    },
    {
        path: '/forgot-password',
        name: 'forgot-password',
        component: () => import('@/views/auth/ForgotPasswordView.vue'),
        meta: { requiresAuth: false, guestOnly: true },
    },
    {
        path: '/reset-password',
        name: 'reset-password',
        component: () => import('@/views/auth/ResetPasswordView.vue'),
        meta: { requiresAuth: false, guestOnly: true },
    },
    {
        path: '/dashboard',
        alias: '/',
        name: 'dashboard',
        component: () => import('@/views/DashboardView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/profile',
        name: 'profile',
        component: () => import('@/views/UserDetailsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/settings',
        name: 'settings',
        component: () => import('@/views/SettingsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/reports/finance',
        name: 'reports.finance',
        component: () => import('@/views/reports/FinanceReportView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/accounts',
        name: 'accounts',
        component: () => import('@/views/accounts/AccountsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/accounts/new',
        name: 'accounts.create',
        component: () => import('@/views/accounts/AccountFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/accounts/:id',
        name: 'accounts.show',
        component: () => import('@/views/accounts/AccountDetailView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/accounts/:id/edit',
        name: 'accounts.edit',
        component: () => import('@/views/accounts/AccountFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/transactions',
        name: 'transactions',
        component: () => import('@/views/transactions/TransactionsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/transactions/new',
        name: 'transactions.create',
        component: () => import('@/views/transactions/TransactionFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/transactions/:id/edit',
        name: 'transactions.edit',
        component: () => import('@/views/transactions/TransactionFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/loans',
        name: 'loans',
        component: () => import('@/views/loans/LoansView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/loans/new',
        name: 'loans.create',
        component: () => import('@/views/loans/LoanFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/loans/:id',
        name: 'loans.show',
        component: () => import('@/views/loans/LoanDetailView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/loans/:id/edit',
        name: 'loans.edit',
        component: () => import('@/views/loans/LoanFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/credit-cards',
        name: 'credit-cards',
        component: () => import('@/views/credit-cards/CreditCardsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/credit-cards/new',
        name: 'credit-cards.create',
        component: () => import('@/views/credit-cards/CreditCardFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/credit-cards/:id',
        name: 'credit-cards.show',
        component: () => import('@/views/credit-cards/CreditCardDetailView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/credit-cards/:id/edit',
        name: 'credit-cards.edit',
        component: () => import('@/views/credit-cards/CreditCardFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/subscriptions',
        name: 'subscriptions',
        component: () => import('@/views/subscriptions/SubscriptionsView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/subscriptions/new',
        name: 'subscriptions.create',
        component: () => import('@/views/subscriptions/SubscriptionFormView.vue'),
        meta: { requiresAuth: true },
    },
    {
        path: '/subscriptions/:id/edit',
        name: 'subscriptions.edit',
        component: () => import('@/views/subscriptions/SubscriptionFormView.vue'),
        meta: { requiresAuth: true },
    },
];
